const drinks = [
  {
    id: 1,
    name: "Fernet Branca",
    desc: "Milán. En su primer laboratorio de la Porta Nuova, Bernardino Branca, un singular autodidacta, obtiene una bebida única producto  de la sabia combinación de hierbas, cortezas, raíces y frutos macerados en alcohol. Cuenta con un colaborador, el Dr. Fernet y Bernardino decide unir sus nombres para bautizar a su reciente creación. Nacía Fernet Branca. Con el tiempo se convertiría en un producto y una marca que trascendería las fronteras de Italia para expandirse  por el mundo",
    stock: 57,
    price: 989,
    image: "https://i.ibb.co/XSn59D4/fernet.png",
    nCategory: 2,
  },
  {
    id: 2,
    name: "Fernet Branca Menta",
    desc: "Milán. En su primer laboratorio de la Porta Nuova, Bernardino Branca, un singular autodidacta, obtiene una bebida única producto  de la sabia combinación de hierbas, cortezas, raíces y frutos macerados en alcohol. Cuenta con un colaborador, el Dr. Fernet y Bernardino decide unir sus nombres para bautizar a su reciente creación. Nacía Fernet Branca. Con el tiempo se convertiría en un producto y una marca que trascendería las fronteras de Italia para expandirse  por el mundo",
    stock: 63,
    price: 995,
    image: "https://i.ibb.co/QmGgrtV/branca-menta-ricetta-italiana-750ml.png",
    nCategory: 2,
  },
  {
    id: 3,
    name: "Carpano Rosso",
    desc: "Tiene el clásico sabor del Vermut de Torino. El primer impacto es dulce, asociado al caramelo y a la naranja; en una segunda instancia aparece la parte vinosa y mineral de la bebida, para terminar con el amargo de los más cuidados botánicos. Es parte de los mejores cócteles de la historia, pero no solo es un ingrediente, sino queCarpano Rosso es un producto en sí mismo, un perfecto aperitivo.",
    stock: 29,
    price: 515,
    image: "https://i.ibb.co/vkSFFtC/carpano.png",
    nCategory: 14,
  },
  {
    id: 4,
    name: "Antica Fórmula",
    desc: "Elaborado con vainilla y azafrán, su fórmula permanece intacta -y secreta- desde hace 230 años. Ideal para tomar con un poquito de hielo y una rodaja de naranja, ya se puede conseguir también en las barras más selectas de nuestro país.",
    stock: 17,
    price: 9887,
    image: "https://i.ibb.co/CwJybpb/antica.png",
    nCategory: 14,
  },
  {
    id: 5,
    name: "Sernova Wild Berrie",
    desc: "Sernova es un vodka de estilo italiano, que cuenta con un proceso de elaboración sofisticado que da como resultado un producto super premium. Es un vodka elegante y delicado, ideal para divertirse y pasarla bien disfrutando de un producto de altísima calidad. Su nombre es el resultado de la fusión de «Novare Serbando», lema de Fratelli Branca destilerías.A diferencia de otros vodkas, el proceso de producción de Sernova consta de 7 destilaciones y 3 filtraciones, durante las cuales se refina y perfecciona. Además, es el único vodka del mercado local que para su proceso de filtrado emplea diamantes negros para asegurar un producto neutro y puro.",
    stock: 44,
    price: 938,
    image: "https://i.ibb.co/8mHy7rN/sernova.png",
    nCategory: 17,
  },
  {
    id: 6,
    name: "Sernova Fresh Citrus",
    desc: "Sernova es un vodka de estilo italiano, que cuenta con un proceso de elaboración sofisticado que da como resultado un producto super premium. Es un vodka elegante y delicado, ideal para divertirse y pasarla bien disfrutando de un producto de altísima calidad. Su nombre es el resultado de la fusión de «Novare Serbando», lema de Fratelli Branca destilerías.A diferencia de otros vodkas, el proceso de producción de Sernova consta de 7 destilaciones y 3 filtraciones, durante las cuales se refina y perfecciona. Además, es el único vodka del mercado local que para su proceso de filtrado emplea diamantes negros para asegurar un producto neutro y puro.",
    stock: 23,
    price: 938,
    image: "https://i.ibb.co/g3fCj4v/sernova-fresh-citrus-700ml.png",
    nCategory: 17,
  },
  {
    id: 7,
    name: "Highland Park 18 años",
    desc: "Es un whisky de una sola malta proveniente del norte de Escocia, añejado 18 años en barricas 100% sazonadas con jerez tanto de roble americano como europeo, usando turba aromática, única en su estilo.",
    stock: 11,
    price: 81381,
    image: "https://i.ibb.co/80DyJb7/whiskey.png",
    nCategory: 5,
  },
  {
    id: 8,
    name: "The Macallan Edition N°6",
    desc: "El sexto y ultimo lanzamiento del The Macallan Edition Series. Edition No. 6 tiene un empaque azul brillante e intenso en homenaje al Río Spey.",
    stock: 14,
    price: 82170,
    image: "https://i.ibb.co/4fpKdjk/the-macallan-edition-n6.png",
    nCategory: 5,
  },
  {
    id: 9,
    name: "Borghetti Licor de Café 700ml.",
    desc: "Licor Borghetti nació en Ancona, Italia, en 1860. Ugo Borghetti, sensible a los gustos de la época, observó la demanda de una bebida vigorizante que mantuviera las propiedades del café y que pudiera disfrutarse a cualquier hora del día. Y así fue que creó un licor al que bautizó con su propio apellido. Licor Borghetti es hoy la bebida centenaria con carácter, que respeta la receta original y utiliza el mismo método de elaboración del “café expresso”.",
    stock: 33,
    price: 1684,
    image: "https://i.ibb.co/z7HMV35/borghetti-licor-de-cafe-700ml.png",
    nCategory: 3,
  },
  {
    id: 10,
    name: "Grappa Candolini Bianca",
    desc: "Esta es una de las más antiguas marcas de grappa de Italia, producida a partir de la destilación de una selección de uvas, respetando la tradición en su elaboración y satisfaciendo consumidores desde 1898. Reconocida globalmente por su inconfundible sabor y su botella de forma oval que representa la promesa de un producto completo, delicado y placentero. Grappa Candolini Bianca concede un sofisticado estilo a los tragos que invita a descubrir.",
    stock: 24,
    price: 6151,
    image: "https://i.ibb.co/bd0KFPK/grappa-candolini-bianca-1000ml.png",
    nCategory: 3,
  },
  {
    id: 11,
    name: "Liquore Strega Limoncello",
    desc: "Liquore Strega Limoncello 700ml",
    stock: 7,
    price: 3969,
    image: "https://i.ibb.co/rtsxPkY/liquore-strega-limoncello-700ml.png",
    nCategory: 3,
  },
  {
    id: 12,
    name: "Combo Previa",
    desc: "1 Botella de Branca 750ml. + 1 botella de Vodka Sernova 700cl + 1 Coca cola 2250 + 1 Shweppes Pomelo 1500cc de Regalo ",
    stock: 24,
    price: 1830,
    image: "https://i.ibb.co/1LNSCFF/combo-previa.png",
    nCategory: 8,
  },
  {
    id: 13,
    name: "Combo Pack Rob Roy",
    desc: "1 botella de Antica Formula + 1 Botella The Macallan 12 años Triple Cask",
    stock: 12,
    price: 39591,
    image: "https://i.ibb.co/xfkGWHN/rob-roy.png",
    nCategory: 8,
  },
  {
    id: 14,
    name: "Combo Punt E Mes",
    desc: "2u. Punt E Mes + 2 copas 250cc",
    stock: 22,
    price: 1390,
    image: "https://i.ibb.co/WydYbqS/combo-punt-e-mes.png",
    nCategory: 8,
  },
];

module.exports = {
  drinks,
};
